### ISSUE TITLE
Project64 Download Fails

### ISSUE THREAD

**Issue by chemscobra** [Rosalie241/BetterMajorasMaskInstaller#15]
Im when I start the installer, it fails to download Project64
![image](https://user-images.githubusercontent.com/2581610/123516046-26278880-d668-11eb-8102-36d726bc6a33.png)

**Comment by Rosalie241** [comment]
Can you try reproducing the issue with the following executable?

[BetterMajorasMaskInstaller.zip](https://github.com/Rosalie241/BetterMajorasMaskInstaller/files/6720458/BetterMajorasMaskInstaller.zip)

**Comment by chemscobra** [comment]
It shows this message instead.
![image](https://user-images.githubusercontent.com/2581610/123521886-6ba77e00-d687-11eb-9dde-4361da37ad98.png)

**Comment by Rosalie241** [comment]
I have no idea what'd cause such an issue sadly, it's not my fault or anything.

someone else had the same issue as you, we tried multiple things but none worked, I'm sorry for not being able to help further.

**Comment by chemscobra** [comment]
I see, well don't worry about it. Maybe the issue is related to some WIN10 update or something. Gonna check If I can reproduce this on multiple machines and investigate more.  Thanks for your help and this nice installer.

**Comment by chemscobra** [comment]
UPDATE. It seems that the problem is related to the ISP. The installer works perfect under a VPN connection

**Comment by Rosalie241** [comment]
what ISP do you have?

**Comment by Rosalie241** [comment]
> 
> 
> UPDATE. It seems that the problem is related to the ISP. The installer works perfect under a VPN connection

another user had the same issue and the same solution worked, really weird..

**Comment by Zergei** [comment]
this issues is happening again with the new release pls check the problem

**Comment by Rosalie241** [comment]
> this issues is happening again with the new release pls check the problem

What do you mean again? It was never fixed afaik.

**Comment by Adrianni** [comment]
I also experience failure with download of project 64, but with a different error: (my highlight and text in bold below)

Downloading Project64...
Downloading Project64 Failed
Det oppsto én eller flere feil. **(translated from norwegian: "One or more error occured")**
   ved System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   ved System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   ved System.Threading.Tasks.Task`1.get_Result()
   ved AppVeyorApi.AppVeyor.getApiData(String url)
   ved AppVeyorApi.AppVeyor.getJobId()
   ved AppVeyorApi.AppVeyor.GetLatestArtifacts()
   ved BetterMajorasMaskInstaller.ComponentDownloader.AppVeyorUrlInfo(UrlInfo urlInfo)
   ved BetterMajorasMaskInstaller.ComponentDownloader.DownloadComponent(InstallerComponent& component, String directory)

Downloading Project64... (**retry**)
Downloading Project64 Failed
Cannot find artifact containing "Win32" in the filename
   ved BetterMajorasMaskInstaller.ComponentDownloader.AppVeyorUrlInfo(UrlInfo urlInfo)
   ved BetterMajorasMaskInstaller.ComponentDownloader.DownloadComponent(InstallerComponent& component, String directory)

**Comment by GhostlyDark** [comment]
@Adrianni Are you using the newest release of the installer (v4.0.1)? It sounds like an issue that has been long solved.

**Comment by Adrianni** [comment]
@GhostlyDark: This is embarrassing. I did not download the newest release. My bookmark was to an older version. Thanks @Rosalie241  for this awesome project <3

**Comment by SomberOfSolace** [comment]
I've been having a similar problem if it helps my ISP is time warner cable.
![yers](https://user-images.githubusercontent.com/90954177/133879321-64fd513c-0a15-4779-81e6-0bb8ee2b8e75.PNG)

**Comment by halian** [comment]
I'm having this issue on Windows 10 with Charter Spectrum internet. Here's my install log:

```
Downloading Project64...
Downloading Project64 Failed
An exception occurred during a WebClient request.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BetterMajorasMaskInstaller.ComponentDownloader.<DownloadComponent>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BetterMajorasMaskInstaller.Window.DownloadInstallComponents.<DownloadAllComponents>d__10.MoveNext()
```

**Comment by SaintBalor** [comment]
Downloading Project64...
Downloading Project64 Failed
Cannot find artifact containing "Win32" in the filename
   at BetterMajorasMaskInstaller.ComponentDownloader.AppVeyorUrlInfo(UrlInfo urlInfo)
   at BetterMajorasMaskInstaller.ComponentDownloader.<DownloadComponent>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BetterMajorasMaskInstaller.Window.DownloadInstallComponents.<DownloadAllComponents>d__10.MoveNext()

Right at the start... VPN doesn't work... at least not Nord VPN... tried with connections in the US and in Brazil

**Comment by GhostlyDark** [comment]
> Downloading Project64... Downloading Project64 Failed Cannot find artifact containing "Win32" in the filename at BetterMajorasMaskInstaller.ComponentDownloader.AppVeyorUrlInfo(UrlInfo urlInfo) at BetterMajorasMaskInstaller.ComponentDownloader.d__17.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at BetterMajorasMaskInstaller.Window.DownloadInstallComponents.d__10.MoveNext()
> 
> Right at the start... VPN doesn't work... at least not Nord VPN... tried with connections in the US and in Brazil

AppVeyor builds expired as there was no activity on Project64 since exactly 1 month. A fallback has been added, so the download should work again.
