### ISSUE TITLE
Unable to download Project 64

### ISSUE THREAD

**Issue by Stellarvideo588** [Rosalie241/BetterMajorasMaskInstaller#17]
When I attempted to start the download it gave me this error 

Downloading Project64...
Downloading Project64 Failed
Cannot find artifact containing "Win32" in the filename
   at BetterMajorasMaskInstaller.ComponentDownloader.AppVeyorUrlInfo(UrlInfo urlInfo)
   at BetterMajorasMaskInstaller.ComponentDownloader.DownloadComponent(InstallerComponent& component, String directory)

**Comment by Rosalie241** [comment]
Are you using the latest version of the installer? Try re-downloading the latest version if you're unsure.

**Comment by Rosalie241** [comment]
can't reproduce & no reply since August, closing.
